[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
docsign = "CvQLJvzRYKbua7unJYMvybGtq6eXfUxBqqqdEgusY65i"

[programs.devnet]
docsign = "Am3fC5dUyB9wCEvpLPEZfiUiRGjgWhUwooDemiZWkhJz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
url = "https://devnet.helius-rpc.com/?api-key=a6a2d071-b38f-421a-a2a2-17e930551127"
wallet = "~/.config/solana/futEr6crxky587rKdqa8pVraFgEQCwadaYg3sPmxWNA.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
